# Generated by Django 3.1.4 on 2021-11-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport', '0002_auto_20211119_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
